# Generated by Django 4.0.4 on 2022-09-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_options_remove_producto_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion_ingles',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_ingles',
        ),
    ]
