# Generated by Django 4.0.4 on 2022-09-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_descripcion_ingles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ventas',
        ),
    ]
