# Generated by Django 4.0.4 on 2022-12-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_b2b',
            field=models.FloatField(default=0),
        ),
    ]
