# Generated by Django 4.0.4 on 2022-09-20 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': '07 - Bancos',
            },
        ),
        migrations.CreateModel(
            name='ConceptoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto Obligación')),
                ('en_experimento', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Concepto de venta',
                'verbose_name_plural': '11 - Conceptos de venta',
            },
        ),
        migrations.CreateModel(
            name='DatosOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255)),
                ('organismmo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('logotipo', models.ImageField(upload_to='imagenes/')),
                ('presidente', models.CharField(max_length=255)),
                ('contador', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=255)),
                ('ircc', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Datos de la Organización',
                'verbose_name_plural': '00 - Datos de la Organización',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': '08 - Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255)),
                ('reeup', models.CharField(max_length=255, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('nit', models.CharField(blank=True, max_length=255, null=True)),
                ('ircc', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Entidad/Persona Natural',
                'verbose_name_plural': '06 - Entidades/Personas Naturales',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contable', 'Moneda Contable'), ('otras', 'Otras Monedas')], max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('siglas', models.CharField(max_length=255)),
                ('tasa', models.FloatField()),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': '10 - Monedas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('numero', models.PositiveIntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número')),
                ('direccion', models.TextField(verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(max_length=255)),
                ('nro_indentidad', models.CharField(max_length=255, unique=True, verbose_name='Nro. Identidad')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': '03 - Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254)),
                ('reeup', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': '01 - Unidades',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.ejercicio')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': '09 - Períodos',
            },
        ),
        migrations.CreateModel(
            name='Custodio',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodios_unidad', to='configuracion.unidad')),
            ],
            options={
                'verbose_name': 'Custodio',
                'verbose_name_plural': '05 - Custodios',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('clave', models.CharField(default='001', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_unidad', to='configuracion.unidad')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': '02 - Área',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('jefe_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes_jefe_almacen', to='configuracion.trabajador', verbose_name='Jefe de Almacén')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes_unidad', to='configuracion.unidad')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': '04 - Almacenes',
            },
        ),
    ]
