# Generated by Django 4.0.4 on 2022-09-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': '02 - Áreas'},
        ),
        migrations.AlterModelOptions(
            name='conceptoventa',
            options={'verbose_name': 'Concepto de venta', 'verbose_name_plural': '12 - Conceptos de venta'},
        ),
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': '09 - Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': '11 - Monedas'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Período', 'verbose_name_plural': '10 - Períodos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': '08 -Sucursales'},
        ),
        migrations.AlterField(
            model_name='custodio',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='custodio',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='custodio',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custodios_unidad', to='configuracion.unidad'),
        ),
        migrations.AlterField(
            model_name='datosorganizacion',
            name='telefono',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='correo',
            field=models.EmailField(blank=True, help_text='Opcional', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='direccion',
            field=models.TextField(blank=True, help_text='Opcional', null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='ircc',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nit',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='pais',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='provincia',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='tasa',
            field=models.FloatField(default=1, help_text='Establecer en 1 si se está insertando una moneda contable'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='reeup',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True, unique=True),
        ),
    ]
