# Generated by Django 4.0.4 on 2022-09-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_area_options_alter_conceptoventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodio',
            name='trabajador',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.trabajador'),
        ),
    ]
