# Generated by Django 4.0.4 on 2022-09-21 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_custodio_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodio',
            name='trabajador',
        ),
        migrations.AlterField(
            model_name='custodio',
            name='codigo',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='custodio',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='custodio',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodios_unidad', to='configuracion.unidad'),
        ),
    ]
