# Generated by Django 4.0.4 on 2022-09-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_remove_custodio_trabajador_alter_custodio_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptoventa',
            options={'verbose_name': 'Concepto de venta', 'verbose_name_plural': '11 - Conceptos de venta'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': '10 - Monedas'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': '08 - Sucursales'},
        ),
    ]
