# Generated by Django 4.0.4 on 2022-10-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_alter_conceptoventa_options_alter_moneda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosorganizacion',
            name='llave',
            field=models.CharField(default='a', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosorganizacion',
            name='servidor',
            field=models.CharField(default='1', max_length=800),
            preserve_default=False,
        ),
    ]
