# Generated by Django 4.0.4 on 2022-10-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_datosorganizacion_llave_datosorganizacion_servidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosorganizacion',
            old_name='llave',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='datosorganizacion',
            old_name='servidor',
            new_name='server',
        ),
        migrations.AddField(
            model_name='datosorganizacion',
            name='test',
            field=models.BooleanField(default=False, verbose_name='Entorno de prueba'),
            preserve_default=False,
        ),
    ]
