# Generated by Django 4.0.4 on 2022-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_rename_organismmo_datosorganizacion_organismo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosorganizacion',
            name='bills_dir',
            field=models.CharField(default='F:\\Facturas\\', max_length=500, verbose_name='Dirección para guardar las facturas'),
            preserve_default=False,
        ),
    ]
