# Generated by Django 4.0.4 on 2022-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_datosorganizacion_bills_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosorganizacion',
            name='ruta_stream',
            field=models.CharField(default='http://192.168.43.1:8080/video', max_length=600, verbose_name='Dirección de transmisión de video'),
        ),
    ]
