# Generated by Django 4.0.5 on 2022-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_proveedorpropio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='reeup',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True, unique=True),
        ),
    ]
