# Generated by Django 4.0.4 on 2022-09-20 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
        ('inventario', '0001_initial'),
        ('configuracion', '0001_initial'),
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('numero_serie', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Número de Serie')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('tipo_factura', models.CharField(max_length=500, verbose_name='Bienes y Servicios')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talones', to='codificadores.tipotalon')),
            ],
            options={
                'verbose_name': 'Talón',
                'verbose_name_plural': '01 - Talones',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('tasa', models.FloatField()),
                ('fecha', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('subtotal_servicios', models.FloatField()),
                ('subtotal_productos', models.FloatField()),
                ('total', models.FloatField()),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_comercial', to='codificadores.comercial')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cuenta_bancaria', to='codificadores.cuentabancaria')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_entidad', to='configuracion.entidad')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_forma_pago', to='codificadores.formapago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_moneda', to='configuracion.moneda')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_operacion', to='codificadores.operacion')),
                ('talon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_talon', to='facturacion.talon')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': '02 - Facturas',
            },
        ),
        migrations.CreateModel(
            name='ComponenteServicioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('001', 'Servicio de transportación')], max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('recargo', models.FloatField()),
                ('descuento', models.FloatField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_servicio', to='precios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ComponenteProductoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('001', 'B to B'), ('002', 'Online'), ('003', 'Pago Anticipado'), ('004', 'Pago en el extranjero')], max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('recargo', models.FloatField()),
                ('descuento', models.FloatField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_almacen', to='configuracion.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_producto', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
