# Generated by Django 4.0.4 on 2022-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_componenteproductofactura_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='subtotal_productos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal_servicios',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
