# Generated by Django 4.0.4 on 2022-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_factura_subtotal_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componenteproductofactura',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='componenteproductofactura',
            name='recargo',
            field=models.FloatField(default=0),
        ),
    ]
