# Generated by Django 4.0.4 on 2022-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_remove_componenteserviciofactura_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha'], 'verbose_name': 'Factura', 'verbose_name_plural': '02 - Facturas'},
        ),
        migrations.AddField(
            model_name='factura',
            name='faltantes',
            field=models.TextField(default='--------------------------------------------------'),
        ),
    ]
