# Generated by Django 4.0.4 on 2022-10-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_factura_options_factura_faltantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='faltantes',
            field=models.TextField(default='------------------------------------------------------------------------------------------------------------------------------------------------------'),
        ),
    ]
