# Generated by Django 4.0.4 on 2022-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_factura_faltantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='nota',
            field=models.TextField(default=''),
        ),
    ]
