# Generated by Django 4.0.4 on 2022-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_factura_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='nota',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
