# Generated by Django 4.0.4 on 2022-10-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_factura_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteproductofactura',
            name='settled_import',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='componenteserviciofactura',
            name='settled_import',
            field=models.FloatField(default=0),
        ),
    ]
