# Generated by Django 4.0.4 on 2022-10-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_componenteproductofactura_settled_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='backup_bill',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
