# Generated by Django 4.0.4 on 2022-10-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_factura_exportada_como_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='exportada_como',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
