# Generated by Django 4.0.4 on 2022-09-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('um', models.CharField(max_length=255, verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': '01 - Servicios',
            },
        ),
    ]
