# Generated by Django 4.0.4 on 2022-09-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': '01 - Cargos',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=255, verbose_name='Forma de Pago')),
                ('tipo', models.CharField(choices=[('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('gratis', 'Gratis'), ('otras', 'Otras Formas de Pago')], max_length=255, verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': '04 - Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': '05 - Operaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoTalon',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('factura', 'Factura'), ('folio', 'Folio Preimpreso')], max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Talón',
                'verbose_name_plural': '07 - Tipos de Talón',
            },
        ),
        migrations.CreateModel(
            name='PersonalAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('ci', models.CharField(max_length=255, verbose_name='Carnet de Identidad')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizados_cargo', to='codificadores.cargo')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizados_entidad', to='configuracion.entidad')),
            ],
            options={
                'verbose_name': 'Personal Autorizado',
                'verbose_name_plural': '03 - Personal Autorizado',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=500)),
                ('codigo_intercambio', models.CharField(max_length=500, verbose_name='Código de Intercambio')),
                ('nombre', models.CharField(max_length=255)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias_moneda', to='configuracion.moneda')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias_sucursal', to='configuracion.sucursal')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': '06 - Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('ci', models.CharField(max_length=255, verbose_name='Carnet de Identidad')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comerciales_cargo', to='codificadores.cargo')),
            ],
            options={
                'verbose_name': 'Comercial',
                'verbose_name_plural': '02 - Comerciales',
            },
        ),
    ]
