# Generated by Django 4.0.4 on 2022-09-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercial',
            name='id',
        ),
        migrations.AlterField(
            model_name='comercial',
            name='ci',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Carnet de Identidad'),
        ),
    ]
